# Generated by Django 5.0.7 on 2025-09-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='currency_code',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Card', 'Credit/Debit Card'), ('PayPalAccount', 'PayPal'), ('Venmo', 'Venmo'), ('ApplePay', 'Apple Pay'), ('GooglePay', 'Google Pay'), ('unknown', 'Unknown')], default='Card', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_processor_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paypal_authorization_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paypal_capture_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paypal_payer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paypal_payer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_status',
            field=models.CharField(choices=[('authorized', 'Authorized'), ('settled', 'Settled'), ('settlement_pending', 'Settlement Pending'), ('failed', 'Failed'), ('voided', 'Voided'), ('refunded', 'Refunded')], default='settled', max_length=50),
        ),
    ]
